js/package-lock.json, js/package.json
Since the bqplot alpha release is out, we should update it here. Also updating package-lock.json to get rid of security warnings.
=> Update bqplot dependency to refer to alpha release

js/package.json
@maartenbreddels - does this seem ok? This will hopefully fix the Jupyter Lab install for glue-jupyter.
=> Update version pinnings for bqplot in package.json

bqplot_image_gl/interacts.py, js/lib/BrushEllipseSelector.js, js/lib/BrushEllipseSelectorModel.js, js/lib/index.js, js/package.json, js/webpack.config.js
This is for us a quick way to release https://github.com/bloomberg/bqplot/pull/1050 so we can use it in https://github.com/glue-viz/glue-jupyter/pull/165
This wasn't trivial, so I think it's good to describe the issue a bit, and how it was solved.
d3-selection uses a global `event` variable, which is used in d3-drag. bqplot and bqplot-image-gl both have their own copy of d3, and thus also of this event variable.
This was very difficult to 'see', since the sourcemapping shows the same file for both versions of the library loaded. Using `devtoolModuleFilenameTemplate: 'webpack://bqplot-image-gl/[namespace]/[resource-path]?[loaders]',` in webpack, it makes it easier to see which d3 you are in when debugging.
Initially we had:
```javascript …
```
=> Feat circular brush

js/lib/BrushEllipseSelector.js
This fixes the issue in https://github.com/glue-viz/glue-jupyter/pull/170 that the ellipse model was still being set from a DOM detached interact widget.
=> fix: remove event listeners for drag listening

js/lib/imagegl.js
The D3 color scale was not returning colors as hex strings but in a different form (e.g. `"rgb(50, 255, 30)"`). This PR  adds a helper function to the update_colormap to parse both hex strings and the above rgb strings. This is part of issue https://github.com/glue-viz/glue-jupyter/issues/76.
=> Fix parsing of D3 color strings for color maps

js/package.json
This is the other side of https://github.com/bqplot/bqplot/pull/1276 so we can read events, which enables the MouseInteraction to work in jlab3.
=> fix(lab3): enable deduplication of d3-selection, and do not bundle

examples/mouse.ipynb, js/lib/MouseInteraction.js
this gives us keydown and keyup event support, similar to ipyevents we grab focus when the mouse moves into the div element of the Figure. Note that we also send the last mouse coordinates with the key events.
=> feat: keydown/keyup event support

bqplot_image_gl/interacts.py, examples/mouse.ipynb, js/lib/MouseInteraction.js
For instance to make MouseInteractions work with PanZoom, for this specific case to work
we should not listen to the drag events, and for this we also need
to filter on those.
Closes #42
Closes #43
cc @pllim
=> feat: compose MouseInteraction with other interacts

js/lib/MouseInteraction.js
This was because the display:none caused us to not have any events.
The reason to add this is to not 'eat' mouse events from the 'next'
interact. However, a better solution is to have the 'next', be added
second in the DOM.
Fixes https://github.com/glue-viz/glue-jupyter/pull/213 for when `next` is set to None
=> fix: if no next interact was present, we would not get events

js/lib/MouseInteraction.js
Similar issue and solution as https://github.com/bqplot/bqplot/pull/1340
=> fix: fallback to window.event if d3.event is null due to duplicate d3-selection module

bqplot_image_gl/viewlistener.py, examples/viewlistener.ipynb, js/lib/ViewListener.js, js/lib/index.js
@astrofrog I did not test this a lot, but you can try out if this works as you expect:
```
from bqplot_image_gl.viewlistener import ViewListener
import ipywidgets as widgets
slider = widgets.FloatSlider()
slider
vl = ViewListener(widget=slider, css_selector=".ui-slider-handle")
```
=> feat: ViewListener to get dimensions of DOM elements in all views

js/lib/ViewListener.js
Some views such as https://github.com/bqplot/bqplot/blob/1c3c0abb474f4ccd0bbf4620f3a86c0d6c13454b/js/src/Figure.ts#L100 wait for the `displayed` and `layoutPromise` before creating DOM elements. We now wait for these so we don't query the DOM before they are created.
=> fix: wait for view promises to give them time to create the DOM

js/lib/linesgl.js
Since we modify the coordinates in the shaders (using scales), the
coordinates for threejs can mislead it to think it's outside the
frustum/viewport.
Fixes the issues described in https://github.com/glue-viz/glue-jupyter/pull/227
=> fix: do not cull lines

js/lib/MouseInteraction.js
This caused 1 MouseInteraction that would be removed to remove the
event listeners of all other MouseInteractions.
Fixes the issue @kecnry mentioned in https://github.com/spacetelescope/jdaviz/pull/1013 because the domain would not be updated any more.
=> fix: MouseInteraction would remove all listeners in .off

js/lib/MouseInteraction.js
fix: Allow for .next to be a MouseInteraction and clean up its event handlers
We now remove the .drag event handlers, but, because multiple MouseInteractions
share the same DOM node and event name, this will remove all event handlers.
Therefore, if the 'parent' MouseInteraction reattaches its event handlers
when .next changes this is not an issue.
Also, if .next changes quickly, we might attach a stale interaction
because we awaited while in the meantime .next already changed.
This caused event handlers to be added, and never removed.
=> fix: Allow for .next to be a MouseInteraction and clean up its event handlers

js/lib/linesgl.js
LinesGL wasn't respecting visibility toggling from the front end. In non-GL bqplot both the image and lines marks inherit this behavior from `Marks`, but it seems like here it isn't getting inherited properly, since there was already code to do this in `imagegl.js`. This adds the equivalent code to `linesgl.js`, although it would be more elegant to have them both inherit the behavior properly.
=> Fix visibility toggle in LinesGL

js/lib/linesgl.js, js/shaders/scales-delta.glsl, js/shaders/scales-extra.glsl
see scales-delta.glsl for details.
The issues could be exposed using:
```python
import numpy as np
from bqplot import Figure, LinearScale, Axis, ColorScale, Lines
from bqplot_image_gl import LinesGL
import ipywidgets as widgets
N = int(1e5)
x = np.arange(N) * 100 + 1e9
y = np.cumsum(np.random.random(N)*2-1)
y -= y.mean()
scale_x = LinearScale(min=x.min(), max=x.min()+1, allow_padding=False)
scale_y = LinearScale(allow_padding=False)
scales = {'x': scale_x, 'y': scale_y}
axis_x = Axis(scale=scale_x, label='x')
axis_y = Axis(scale=scale_y, label='y', orientation='vertical')
line_gl = LinesGL(x=x, y=y, scales=scales, colors=['orange'])
marks = [line_gl]
figure = Figure(scales=scales, axes=[axis_x, axis_y], marks=marks)
display(figure)
```
Fixes …
=> fix: allow over 8 orders of magnitude in zooming

bqplot_image_gl/__init__.py
Jdaviz is unable to use the latest release.
```File .../bqplot_image_gl/__init__.py:1, in <module>
----> 1 from ._version import version_info, __version__  # noqa
3 from .imagegl import *  # noqa
4 from .linesgl import *  # noqa
ImportError: cannot import name 'version_info' from 'bqplot_image_gl._version' 
```
cc @maartenbreddels @rosteen @orifox
=> BUG: Remove non-existing import

bqplot_image_gl/interacts.py
I was getting a `DeprecationWarning` in the tests for astrowidgets because `bqplot_image_gl` was using an instance instead of a class.
This change fixes the warning.
```python-traceback
collected 0 items / 1 error
======================================================================= ERRORS ========================================================================
_______________________________________________ ERROR collecting astrowidgets/tests/test_bqplot_api.py ________________________________________________
astrowidgets/tests/test_bqplot_api.py:10: in <module>
from astrowidgets.bqplot import ImageWidget, ALLOWED_CURSOR_LOCATIONS
astrowidgets/bqplot.py:16: in <module>
from bqplot_image_gl.interacts import (MouseInteraction,
../../miniconda3/envs/awid/lib/python3.10/site-packages/bqplot …
```
=> Use instance instead of class for trait

bqplot_image_gl/viewlistener.py, js/lib/ViewListener.js
Stores timestamps `resized_at` and `focused_at` in `view_data`. This is useful to track which viewer figures should have their shape set based on.
@maartenbreddels and others I welcome discussion / feedback on the focus portion in particular:
- Should we also track the last point at which focus entered a view?
- Is there any need to remove the eventListener from window?
=> feat: resize & focus tracking in view_data
